<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## **Extra Resources**

Derivative of the Sigmoid function - https://towardsdatascience.com/derivative-of-the-sigmoid-function-536880cf918e

Perceptron lecture video https://www.youtube.com/watch?v=DrdnfQQnpCM&feature=youtu.be

Unit 4 Week 1 Sprint Challenge Review - In Unit 4-Week1 folder

Neural networks 3 blue 1 brown explaination  - https://www.youtube.com/watch?v=aircAruvnKk&feature=youtu.be

Neural network youtube playlist - https://www.youtube.com/playlist?list=PLxt59R_fWVzT9bDxA76AHm3ig0Gg9S3So

Weights initialization and best practices - https://medium.com/usf-msds/deep-learning-best-practices-1-weight-initialization-14e5c0295b94

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### **Input Layer**: 

The layer that receives data such as feature name. The only layer that you interact with. 

### **Hidden Layer**: 

The layer between the input layer and output layer that process data and information but you don't interact with it directly. These layers recieves weights and bias from input layer or from the hidden layer before then. Then they pass the new and updated weights to the next hidden layer or to the output layer. 

### **Output Layer:**
The layer that processes and spits out the final values. 

### **Neuron:**

Neurons Takes input values, multiple the weights by the input values, sum up the result of the multiplication, and push the sum to the activation function, what comes out of the activation function is the output which could be the result or the input of the next layer. 

### **Weight:** 

The weight is the value that you multiply the input by to get the next weight or to get the prediction. The weight is like the coefficient in a linear equation. Weight of all inputs are added together to get the cumulative weight of the new neuron. 

### **Activation Function:** 

Used to modify the neuron/node so that the results from the neuron is in a format that is consistent with the type of problem being solved. Activation function also decides how much data and in what format to pass that data to the next neuron. Every node has an activation function. 

### **Node Map:** 

The map that shows the structure of the neurons network

### **Perceptron:**

The smallest/simplest form of a neuron network. It consist of a single neuron/node with nothing else. 


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### 

a,c,d = data
w = weight

**In input layer**
1. The input layer receives a data = a, c, d

When the data goes to the first hidden layer or to the output layer if there are no hidden layers, 

2. That data is multiplied by a weight. (w x a), (w x c), (w x d)
3. All the multiplied weight is added together along with the bias value (w x a) + (w x c) + (w x d) + bias
4. The result of this multiplication will be modified by an activation function.
5. The result from the activation function will be the output of the previous layer and the input of the next layer. Or if the previous layer was the last layer, then the result from the activation function will be the result. 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
##### Your Code Here #####

df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [3]:
# define what the output is supposed to be
y = df['y'].to_list()
output = [[x] for x in y]
output

[[1], [1], [1], [0]]

Sigmoid function

![Sigmoid function](https://www.researchgate.net/profile/Knut_Kvaal/publication/239269767/figure/fig2/AS:643520205430784@1530438581076/An-illustration-of-the-signal-processing-in-a-sigmoid-function.png)

In [4]:
# define the sigmoid activation function which put the outputs as a 0 or 1

def sigmoid(x):
    return 1/(1 + np.exp(-x))

# define the derivative of the sigmoid function

def sigmoid_der(x):
    # sigmoid of x
    sx = sigmoid(x)
    # derivative of x
    dx = sx * (1-sx)
    return dx

In [5]:
# initialize random weights for inputs
# 3 inputs means 3 random weights

import numpy as np

# random 3 by 1 matrix. This matrix is a random number between 0 and 1
# multiply this 0 and 1 by 2. Then, subtract 1 from it. 

# documentation on random.random 
# https://docs.python.org/dev/library/random.html#random.random

weights = 2*np.random.random((3,1)) - 1

In [6]:
(np.random.random() * 2) - 1

-0.4243318737857471

In [7]:
weights

array([[ 0.45205702],
       [-0.42658744],
       [ 0.87151447]])

In [8]:
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [9]:
# weighted sum of inputs and the weights
weighted_sum = np.dot(df, weights)
weighted_sum

array([[0.87151447],
       [1.32357149],
       [0.44492703],
       [0.02546959]])

In [10]:
# how the calculation is done
# x(weight 1) + x2(weight2) + y(weight3) = output
0.31741796 + -0.83987352

-0.52245556

In [11]:
# activated function version of the output

activated_output = sigmoid(weighted_sum)
activated_output

array([[0.70506073],
       [0.7897753 ],
       [0.60943242],
       [0.50636705]])

In [12]:
# find the error between prediction and actual values
error = output - activated_output
error

array([[ 0.29493927],
       [ 0.2102247 ],
       [ 0.39056758],
       [-0.50636705]])

In [13]:
# gradient descent and back progagation

adjustment = error * sigmoid_der(weighted_sum)
adjustment

array([[ 0.06133265],
       [ 0.03490367],
       [ 0.09296467],
       [-0.12657124]])

In [14]:
df.T

# first line of new weight should be 

# 0.04961164 + -0.08699663 + original weight (0.31741796) = 0.28003297

0  1  2  3
x1  0  1  0  1
x2  0  0  1  1
y   1  1  1  0

In [15]:
0.04961164 + -0.08699663 + 0.31741796

0.28003297

In [16]:
# new weights

weights += np.dot(df.T, adjustment)
weights

array([[ 0.36038945],
       [-0.460194  ],
       [ 1.06071546]])

## **How to create a perceptron from scratch.**

In [17]:
# repeat the above process 10,000 times. Update weight 10,000 times 
# and re-do calculations

# the dataframe

import pandas as pd
import numpy as np

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')


# the sigmoid function to be used as activation function. 

def sigmoid(x):
    return 1/(1 + np.exp(-x))

# define the derivative of the sigmoid function

def sigmoid_der(x):
    # sigmoid of x
    sx = sigmoid(x)
    # derivative of x
    dx = sx * (1-sx)
    return dx

# initializing random weights. 

weights = 2*np.random.random((3,1)) - 1

# define what the output is supposed to be
y = df['y'].to_list()
output = [[x] for x in y]

# repeat the above process 10,000 times. Update weight 10,000 times 
# and re-do calculations

for repeat in range(10000):
    
    # weighted sum of inputs and weights
    
    weighted_sum = np.dot(df, weights)
    
    # activate values
    activated_output = sigmoid(weighted_sum)
    
    # calculate error
    error = output - activated_output
    adjustment = error * sigmoid_der(weighted_sum)
    
    # pdate the weights
    weights += np.dot(df.T, adjustment)
    
print("Weights after training")
print(weights)
    
print("Output after training")
print(activated_output)

Weights after training
[[-2.40958618]
 [-2.41093828]
 [ 7.49032304]]
Output after training
[[0.99944181]
 [0.99382275]
 [0.99381445]
 [0.00799848]]


# **Function to create a simple perceptron**

In [18]:
def perceptron(df, output, weight):
    """Function to create a perceptron which 
    is a single neuron neural network. 
    When provided with a dataframe and 
    what the output is supposed to be
    and the initial weights"""
    
    import numpy as np
    
    # the sigmoid function to be used as activation function. 

    def sigmoid(x):
        return 1/(1 + np.exp(-x))

    # define the derivative of the sigmoid function

    def sigmoid_der(x):
        # sigmoid of x
        sx = sigmoid(x)
        # derivative of x
        dx = sx * (1-sx)
        return dx
    
    for repeat in range(10000):
    
        # weighted sum of inputs and weights

        weighted_sum = np.dot(df, weight)

        # activate values
        activated_output = sigmoid(weighted_sum)

        # calculate error
        error = output - activated_output
        adjustment = error * sigmoid_der(weighted_sum)

        # update the weights
        weight += np.dot(df.T, adjustment)
    
    print("Weights after training")
    print(weights, "\n")

    print("Output after training")
    print(activated_output)
    

    

In [19]:
# trying out the function above

weights = 2*np.random.random((3,1)) - 1

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

output = [[x] for x in df['y']]

perceptron(df, output, weights)

Weights after training
[[-2.41002481]
 [-2.41049147]
 [ 7.49031016]] 

Output after training
[[0.9994418 ]
 [0.99381998]
 [0.99381711]
 [0.00799854]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [20]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [21]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]
feats

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [22]:
# defining x values

x = diabetes[feats]

x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [23]:
y = [[x] for x in diabetes['Outcome']]
y[:5]

[[1], [0], [1], [0], [1]]

In [24]:
# applying scaling function to x dataframe

scaler = MinMaxScaler()

x_scaled = scaler.fit_transform(x)
x_scaled[:2]

array([[0.35294118, 0.74371859, 0.59016393, 0.35353535, 0.        ,
        0.50074516, 0.23441503, 0.48333333],
       [0.05882353, 0.42713568, 0.54098361, 0.29292929, 0.        ,
        0.39642325, 0.11656704, 0.16666667]])

In [25]:
# trying to put scalled function back into a dataset

x2 = pd.DataFrame(columns=feats, data=x_scaled)
x2.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.352941  0.743719       0.590164       0.353535  0.000000  0.500745   
1     0.058824  0.427136       0.540984       0.292929  0.000000  0.396423   
2     0.470588  0.919598       0.524590       0.000000  0.000000  0.347243   
3     0.058824  0.447236       0.540984       0.232323  0.111111  0.418778   
4     0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   

   DiabetesPedigreeFunction       Age  
0                  0.234415  0.483333  
1                  0.116567  0.166667  
2                  0.253629  0.183333  
3                  0.038002  0.000000  
4                  0.943638  0.200000

In [35]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
        # niter = number of iterations
    
    # define the sigmoid function/method
    def __sigmoid(self, x):
        self.x = x
        return 1/(1 + np.exp(-x))
    
    # define the sigmoid derivative method/function
    def __sigmoid_derivative(self, x):
        self.x = x
        # sigmoid of x
        self.sx = sigmoid(x)
        # derivative of x
        self.dx = sx * (1-self.sx)
        return self.dx

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = 2*np.random.random((X.shape[1])) - 1

        for i in range(self.niter):
            # weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights)

            # activate values
            activated_output = sigmoid(weighted_sum)

            # calculate error
            error = y - activated_output
            adjustment = error * sigmoid_derivative(weighted_sum)

            # update the weights
            self.weights += np.dot(X.T, adjustment)
            
        return self.weights


    def predict(self, X):
        """Return class label after unit step"""
        final_weighted_sum = np.dot(X, fit.weights)
        self.final_output = sigmoid(final_weighted_sum)
        return 1.0 if self.final_output >= 0 else 0

In [33]:
y2 = diabetes['Outcome']
y2.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [28]:
y2.shape

(768,)

In [29]:
p = Perceptron()

In [36]:
p.fit(x2, y)

ValueError: shapes (768,8) and (9,) not aligned: 8 (dim 1) != 9 (dim 0)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?